# Generated by Django 5.1.5 on 2025-02-04 18:26

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user_type', models.CharField(choices=[('COOKER', 'Cooker'), ('PROFESSIONAL_CHEF', 'Professional Chef'), ('NUTRITIONIST', 'Nutritionist'), ('NORMAL_USER', 'Normal user')], default='NORMAL_USER', max_length=100)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('country', models.CharField(max_length=100)),
                ('dietary_restrictions', models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('GLUTEN_FREE', 'Gluten free'), ('DAIRY_FREE', 'Dairy free'), ('NUT_FREE', 'Nut free'), ('LOW_CARB', 'Low carb'), ('LOW_FAT', 'Low fat'), ('HALAL', 'Halal'), ('KOSHER', 'Kosher'), ('PALEO', 'Paleo')], default='VEGAN', max_length=100)),
                ('cooking_goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('favorite_tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('biography', models.TextField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('notification_settings', models.JSONField(blank=True, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='users.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
