# Generated by Django 5.1.5 on 2025-02-11 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('GLUTEN_FREE', 'Gluten free'), ('DAIRY_FREE', 'Dairy free'), ('NUT_FREE', 'Nut free'), ('LOW_CARB', 'Low carb'), ('LOW_FAT', 'Low fat'), ('HALAL', 'Halal'), ('KOSHER', 'Kosher'), ('PALEO', 'Paleo')], default=list, null=True, size=None),
        ),
    ]
