# Generated by Django 5.1.5 on 2025-02-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('GLUTEN_FREE', 'Gluten free'), ('DAIRY_FREE', 'Dairy free'), ('NUT_FREE', 'Nut free'), ('LOW_CARB', 'Low carb'), ('LOW_FAT', 'Low fat'), ('HALAL', 'Halal'), ('KOSHER', 'Kosher'), ('PALEO', 'Paleo')], max_length=100, null=True),
        ),
    ]
