# Generated by Django 5.1.5 on 2025-02-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_initial'),
        ('recipes', '0004_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='Ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='Recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('Ingredient__isnull', True), ('Recipe__isnull', False)), models.Q(('Ingredient__isnull', False), ('Recipe__isnull', True)), _connector='OR'), name='recipe_or_ingredient_not_null'),
        ),
    ]
