# Generated by Django 5.1.5 on 2025-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_favorite_ingredient_alter_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='NotificationCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='NotificationType',
            field=models.CharField(choices=[('comment', 'Comment'), ('update_request', 'Update Request')], default='comment', max_length=32),
        ),
    ]
