# Generated by Django 5.1.5 on 2025-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_notification_notificationcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='NotificationType',
            field=models.CharField(choices=[('comment', 'Comment'), ('update_request', 'Update Request')], max_length=32),
        ),
    ]
