# Generated by Django 5.1.5 on 2025-02-20 02:11

import django.core.validators
import rating.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rename_recipe1_rating_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5), rating.models.CustomValidator]),
        ),
    ]
