# Generated by Django 5.1.4 on 2025-02-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
