# Generated by Django 5.1.4 on 2025-02-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_recipeingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=models.ManyToManyField(null=True, to='recipes.ingredient'),
        ),
    ]
